package dev.shadowsoffire.placebo.util;

import dev.shadowsoffire.placebo.events.PlaceboEvents;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.entity.Mob;

/**
 * The side-effecting half of {@code PlaceboEvents.MOB_DESPAWN} on Fabric, shared by the two mixins that fire it.
 * <p>
 * It lives here rather than on the event because NeoForge applies these effects itself, from its own
 * {@code EventHooks.checkMobDespawn}, once the result is carried back to its event. Putting them in the common
 * fire method would run them twice there.
 * <p>
 * Deliberately not in the {@code mixin} package: the Fabric mixin config is generated by listing every class
 * under that tree.
 */
public class DespawnHooks {

    /**
     * Fires the event for {@code mob} and applies whatever the listeners decided.
     *
     * @return true if vanilla's despawn logic should be skipped, matching NeoForge's own return contract.
     */
    public static boolean applyDespawnResult(Mob mob) {
        if (!(mob.level() instanceof ServerLevel level)) {
            return false;
        }
        PlaceboEvents.DespawnResult result = PlaceboEvents.fireMobDespawn(mob, level);
        switch (result) {
            case ALLOW -> mob.discard();
            case DENY -> mob.setNoActionTime(0);
            case DEFAULT -> {}
        }
        return result != PlaceboEvents.DespawnResult.DEFAULT;
    }

}
