package dev.shadowsoffire.placebo.util;

import java.util.Collection;

import org.jetbrains.annotations.Nullable;

import net.minecraft.world.entity.item.ItemEntity;

/**
 * Implemented on vanilla {@code Entity} by {@code EntityDropCaptureMixin}, so that item drops can be diverted
 * into a list instead of going straight into the world.
 * <p>
 * This is the Fabric half of {@code PlaceboEvents.LIVING_DROPS}, and it exists because vanilla never builds a
 * list of an entity's drops — it adds each one as it is produced. NeoForge solves that by patching a
 * {@code captureDrops} field onto {@code Entity}; a mixin can add the same field, which is one of the few
 * things a mixin can do that an access widener cannot.
 * <p>
 * Deliberately not in the {@code mixin} package: the Fabric mixin config is generated by listing every class
 * under that tree, so a plain interface there would be registered as a mixin and fail to apply.
 */
public interface DropCapturer {

    /**
     * The collection drops are currently being diverted into, or null when they should go straight to the world.
     */
    @Nullable
    Collection<ItemEntity> placebo$getCapturedDrops();

    void placebo$setCapturedDrops(@Nullable Collection<ItemEntity> drops);

}
