package dev.shadowsoffire.placebo.util;

import net.minecraft.world.entity.Mob;

/**
 * Implemented on vanilla {@link Mob} by {@code MobSpawnCancelMixin}, supplying the flag NeoForge patches onto
 * {@code Mob} directly.
 * <p>
 * A listener on {@code PlaceboEvents.FINALIZE_SPAWN} that replaces a mob needs to stop the original reaching
 * the world. NeoForge has a field for that and honours it on its own spawn paths; Fabric has neither, so the
 * mixin adds the field and {@code PlaceboFabric} adds the check, on Architectury's {@code EntityEvent.ADD}.
 * <p>
 * Deliberately not in the {@code mixin} package: the mixin config is generated by listing every class there.
 */
public interface SpawnCancelable {

    boolean placebo$isSpawnCancelled();

    void placebo$setSpawnCancelled(boolean cancelled);

}
